services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: testforecastsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: IDnowLOV123!
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/testforecastsdb.sql:/docker-entrypoint-initdb.d/testforecastsdb.sql
    ports:
      - "5434:5432"

volumes:
  db_data:
